seed: 1234
lr: 1e-04
dropout: 0.2
warmup: 1000
num_workers: 4
every_n_epochs: 5
max_prediction_span: 25
max_input_len: 1024
batch_size: 12
eval_batch_size: 8
grad_accum: 4
grad_ckpt: True
fp16: False
attention_window: 512
num_epochs: 60
model_name: allenai/longformer-base-4096
data_dir: /data
output_dir: /saved_models/
clearml_dataset_project_name: datasets/muc4
clearml_dataset_name: muc4-processed-post-eda-v3
clearml_dataset_tags: ["6 Fields", "GTT", "processed"]
task_tags: []
gpu: 1
debug: False
train: True
test: True
remote: True
early_stopping: True
checkpointing: True
trained_model_path: 
queue: compute
role_map: {
    'O': 0,
    'B-Location': 1,
    'I-Location': 2,
    'B-PerpInd': 3,
    'I-PerpInd': 4,
    'B-PerpOrg': 5,
    'I-PerpOrg': 6,
    'B-PhysicalTarget': 7,
    'I-PhysicalTarget': 8,
    'B-HumTarget': 9,
    'I-HumTarget': 10,
    'B-Weapon': 11,
    'I-Weapon': 12,
}
